// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIMO-jjhWOHxgqaXx-Ni2Wx2jjbe94rvs',
    appId: '1:928312412371:web:e35aa6a944330a0239ac26',
    messagingSenderId: '928312412371',
    projectId: 'socialapp-b2a8c',
    authDomain: 'socialapp-b2a8c.firebaseapp.com',
    storageBucket: 'socialapp-b2a8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApX5ygxXOFjlL2FQVyl5WkBwnz_z_HPxU',
    appId: '1:928312412371:android:29011d234b5090ac39ac26',
    messagingSenderId: '928312412371',
    projectId: 'socialapp-b2a8c',
    storageBucket: 'socialapp-b2a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh02xG0iFAg0NeopKMmnpwLAganMuLFNs',
    appId: '1:928312412371:ios:e24aa3c90c89e03439ac26',
    messagingSenderId: '928312412371',
    projectId: 'socialapp-b2a8c',
    storageBucket: 'socialapp-b2a8c.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );
}
